server:
  port: 8081

spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://postgres:5432/taskdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/